### ISSUE TITLE
Would be a great library - if it worked!

### ISSUE THREAD

**Issue by replaysMike** [AlenToma/FastDeepCloner#1]
I have been unable to get this library to work on anything but simple objects. When using without settings it does return a new object, but most of the properties are by reference not as a copy.

**Comment by AlenToma** [comment]
do you have and example project/repo i can test. 
show me the code that you execute.

**Comment by AlenToma** [comment]
closing this issue, have tested the library and its working fine. and there is no example code provided by you so could not se if the problem exist in your code either
