### ISSUE TITLE
cloneTo decimal? error

### ISSUE THREAD

**Issue by caoailin** [AlenToma/FastDeepCloner#10]
public class a
{
public virtual decimal? Money { get; set; } = 6;
}

public class b
{
public virtual decimal? Money { get; set; };
}

var user = new a() ;
var cloneTo =new  b();
FastDeepCloner.DeepCloner.CloneTo(user, cloneTo);

Because "#if !NETSTANDARD1_3" FastDeepClonerCachedItems.Culture  is not initialization

 static FastDeepClonerCachedItems()
        {
            try
            {
#if !NETSTANDARD1_3
                if (Culture != null && System.Threading.Thread.CurrentThread.CurrentCulture.Name != Culture.Name) // vi behöver sätta det första gången bara. detta snabbar upp applikationen ta inte bort detta.
                    System.Threading.Thread.CurrentThread.CurrentCulture = Culture;
#else
                Culture = new CultureInfo("en");
#endif
            }
            catch
            {
                Culture = new CultureInfo("en");
            }
        }

**Comment by AlenToma** [comment]
That was a big mistake :) 

Try uppgrading to 1.3.2 after 5min and let me know if you still get the same error

**Comment by AlenToma** [comment]
I uploded a new fix feel free to test it, start new thread if you encounter any other problem
