### ISSUE TITLE
Copying object with ImageSource type of properties throws exception

### ISSUE THREAD

**Issue by sekulicb** [AlenToma/FastDeepCloner#12]
Hi. I use this library for creating a snapshot of my view model in WPF app. Currently I have few properties that are of type ImageSource. They are bound to the view via INotifyPropertyChanged interface. I noticed that when creating deep copy of my view model, by grouping all the properties in dictionary <string, object>, where string is property name, and object is the value of the property,  

I get the following inner exception:
BitmapMetadata initialization incomplete. | System.Exception {System.InvalidOperationException

Stack trace of inner exception: 
   at System.Windows.Media.Imaging.BitmapMetadata.EnsureBitmapMetadata()
   at System.Windows.Media.Imaging.BitmapMetadata.SetQuery(String query, Object value)
   at System.Windows.Media.Imaging.BitmapMetadata.set_Rating(Int32 value)

Complete stack trace:

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
   at FastDeepCloner.FastDeepClonerProperty.SetValue(Object o, Object value)
   at FastDeepCloner.ReferenceClone.ReferenceTypeClone(Dictionary`2 properties, Type primaryType, Object objectToBeCloned, Object appendToValue)
   at FastDeepCloner.ReferenceClone.Clone(Object objectToBeCloned)
   at FastDeepCloner.ReferenceClone.ReferenceTypeClone(Dictionary`2 properties, Type primaryType, Object objectToBeCloned, Object appendToValue)
   at FastDeepCloner.ReferenceClone.Clone(Object objectToBeCloned)
   at FastDeepCloner.ReferenceClone.Clone(Object objectToBeCloned)
   at FastDeepCloner.DeepCloner.Clone[T](T objectToBeCloned, FieldType fieldType)

**Comment by AlenToma** [comment]
Well, FastDeepCloner is mostly used for classes, and not with those kind of objects.

There was an issue before concern Button and i still game the same answer. 

ImageSource is a really special case and should not be copied the way you are doing it. 

But still if you could create a small project with the issue, i could try and have some time for it and find fix it. 

Otherwise try using something else other then ImageSource

**Comment by AlenToma** [comment]
There is now a fix for this, have a look here https://github.com/AlenToma/FastDeepCloner/blob/master/Documentations/NoneCloneableAttribute.md

**Comment by sekulicb** [comment]
"System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.\r\n ---> System.InvalidOperationException: BitmapMetadata initialization incomplete.\r\n   at System.Windows.Media.Imaging.BitmapMetadata.EnsureBitmapMetadata()\r\n   at System.Windows.Media.Imaging.BitmapMetadata.SetQuery(String query, Object value)\r\n   at System.Windows.Media.Imaging.BitmapMetadata.set_Rating(Int32 value)\r\n   --- End of inner exception stack trace ---\r\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)\r\n   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)\r\n   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)\r\n   at FastDeepCloner.FastDeepClonerProperty.SetValue(Object o, Object value)\r\n   at FastDeepCloner.ReferenceClone.ReferenceTypeClone(Dictionary`2 properties, Type primaryType, Object objectToBeCloned, Object appendToValue)\r\n   at FastDeepCloner.ReferenceClone.Clone(Object objectToBeCloned)\r\n   at FastDeepCloner.ReferenceClone.ReferenceTypeClone(Dictionary`2 properties, Type primaryType, Object objectToBeCloned, Object appendToValue)\r\n   at FastDeepCloner.ReferenceClone.Clone(Object objectToBeCloned)\r\n   at FastDeepCloner.ReferenceClone.Clone(Object objectToBeCloned)\r\n   at FastDeepCloner.DeepCloner.Clone[T](T objectToBeCloned, FieldType fieldType)\r\n

I tried with NoneCloneableAttribute but sometimes it works, sometimes it doesn't

**Comment by AlenToma** [comment]
are you able to write down the class and how you clone it, with some example code.

So i could test it.

**Comment by sekulicb** [comment]
Hi. I will try to be as detailed as possible:

Let say I have my Dto as following:

```     
 public int Id { get; set; }

 public AnotherDTO AnotherDTO { get; set; }

 public Another2DTO Another2DTO { get; set; }

 public string Number{ get; set; }

 public byte[] Image{ get; set; }

 public byte[] Image2{ get; set; }

 public byte[] Image3{ get; set; }

 public byte[] Image4{ get; set; }

 private ImageSource GetImageSource()
 {
       if (Image != null)
       {
            _image = BitmapConvert.FromByteArray(Image);
       }

       return _image;
 }

 public ImageSource ImageSource1
 {
       get => GetImageSource();

       set => _image = value;
  }
```

Now when this gets loaded from the db, I have some helper properties in the same class which helps me present the data on the UI. I'm using WPF by the way, and to show these images I have to convert to ImageSource all the byte[] properties.

So I have two properties, one is Image which is byte[] and second one is UI property called ImageSource1. Of course this goes for all the images in this class. Currently I have 7.

Since this object inherits from INotifyPropertyChanged, it can be presented in the ListBox. Now all rows are loaded and user can interact with the app. When the user is trying to *add new row*, I clone the current state of the View Model for that form, so that if the user takes a picture, and tries to cancel, I can compare the initial state of the View Model with the modified state, and pop up cancel message. I created a small utility class that helps me do just that:

```
public class ViewModelState<T> : IViewModelState<T> where T : BaseViewModel
    {
        public Dictionary<string, object> InitialState { get; set; }

        public string[] ExcludeProperties { get; set; }

        public string[] IncludeProperties { get; set; }

        public void SetInitial(T viewModel)
        {
            InitialState = GetCurrent(viewModel).Clone();
        }

        public void SetInitialInclude(T viewModel)
        {
            InitialState = GetCurrentInclude(viewModel).Clone();
        }

        public async Task<bool> IsDirty(T viewModel)
        {
            var current = GetCurrent(viewModel);

            var areEqual= await Compare(InitialState, current);

            return !areEqual;
        }

        public async Task<bool> IsDirtyForIncluded(T viewModel)
        {
            var current = GetCurrentInclude(viewModel);

            var areEqual = await Compare(InitialState, current);

            return !areEqual;
        }

        public void RevertToInitial(T viewModel)
        {
            var current = viewModel.GetType()
                .GetProperties()
                .Where(el => el.PropertyType != typeof(ICommand) && ExcludeProperties.All(p => p != el.Name));

            foreach (var initProp in InitialState)
            {
                foreach (var c in current)
                {
                    if (c.Name == initProp.Key)
                    {
                        c.SetValue(viewModel, initProp.Value);
                        break;
                    }
                }
            }
        }

        private Dictionary<string, object> GetCurrent(T viewModel)
        {
            var properties = viewModel.GetType()
                .GetProperties()
                .Where(el => el.PropertyType != typeof(ICommand) && ExcludeProperties.All(p => p != el.Name));

            var current = properties.ToDictionary(property => property.Name, property =>
            {
                if (property.CanRead)
                {
                    return property.GetValue(viewModel);
                }
                else
                {
                    return null;
                }
            });

            return current;
        }

        private Dictionary<string, object> GetCurrentInclude(T viewModel)
        {
            var properties = viewModel.GetType()
                .GetProperties()
                .Where(el => el.PropertyType != typeof(ICommand) && IncludeProperties.Any(p => p == el.Name));

            var current = properties.ToDictionary(property => property.Name, property => property.GetValue(viewModel));

            return current;
        }

        public Task<bool> Compare(Dictionary<string, object> source, Dictionary<string, object> current)
        {
            foreach (var src in source)
            {
                foreach (var curr in current)
                {
                    if (src.Key == curr.Key)
                    {
                        var diff = src.Diff(curr, ComparisonOptions.CompareProperties | ComparisonOptions.CompareCollections | ComparisonOptions.TreatEmptyListAndNullTheSame , ".Value.ExtendedProperties.Count");

                        if (diff.Count == 0)
                        {
                            break;
                        }

                        if (diff.Any(d => d.LeftValue == null && IsEmptyString(d.RightValue)))
                        {
                            break;
                        }

                        return Task.FromResult(false);
                    }
                }
            }

            return Task.FromResult(true);
        }

        public bool IsEmptyString(object value)
        {
            if (value is string checkVal)
            {
                return checkVal == string.Empty;
            }

            return false;
        }
    }
```

Now the problem happens when I want to Clone the InitialState and compare it with current data that I have, or when I *Clone already saved row from the db*, and again compare it, if there are any new modification done.

**Comment by sekulicb** [comment]
This is what I use when converting from one type to another:

```
public static class BitmapConvert
    {
        public static BitmapSource FromByteArray(byte[] byteArray)
        {
            if (byteArray == null) return null;

            using (var memoryStream = new MemoryStream(byteArray))
            {
                var decoder = BitmapDecoder.Create(memoryStream, BitmapCreateOptions.PreservePixelFormat, BitmapCacheOption.OnLoad);
                return decoder.Frames[0];
            }
        }

        public static byte[] ImageToByte(Image img)
        {
            var converter = new ImageConverter();

            var clone = (Image) img.Clone();

            return (byte[])converter.ConvertTo(new Bitmap(clone), typeof(byte[]));
        }

        public static void SaveAsImage(byte[] bytearray, string fileName = "image.png")
        {
            using (var image = Image.FromStream(new MemoryStream(bytearray)))
            {
                var pdFolder = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);

                var fullPath = Path.Combine(pdFolder, @"Spry AB", fileName);

                image.Save(fullPath, ImageFormat.Png);
            }
        }

        public static byte[] FromStrokeCollection(StrokeCollection strokes)
        {
            byte[] array;

            using (var memoryStream = new MemoryStream())
            {
                strokes.Save(memoryStream);

                array = memoryStream.ToArray();
            }

            return array;
        }

        public static StrokeCollection FromByteArrayToInkCanvas(byte[] byteArray)
        {
            using (var memoryStream = new MemoryStream(byteArray))
            {
                return new StrokeCollection(memoryStream);
            }
        }

        public static byte[] FromImageSource(ImageSource imageSource)
        {
            if (imageSource == null) return null;

            byte[] bytes;
            var encoder = new PngBitmapEncoder();

            var clone = imageSource.CloneCurrentValue();

            encoder.Frames.Add(BitmapFrame.Create((BitmapSource)clone));

            using (var stream = new MemoryStream())
            {
                encoder.Save(stream);
                bytes = stream.ToArray();
            }

            return bytes;
        }
    }

```

**Comment by AlenToma** [comment]
You need to add `NoneClonable ` to your `ImageSource1`, as i guss there will be the error
