### ISSUE TITLE
Not suitable for large objects

### ISSUE THREAD

**Issue by Sire** [AlenToma/FastDeepCloner#14]
Did some real-life testing and the old [DeepCloner](https://github.com/force-net/DeepCloner) nuget package is much faster, possibly using another technique (IL Emit?). It could also handle ImmutableCollection without crashing.
My benchmark on a complex collection of hierarchical objects (14000 of them):
DeepCloner        6.0 ms
FastDeepCloner  7980.0 ms
(131567% slower)

For small objects, the speed difference is of course negligible, but for large ones, there are better options.

Perhaps their method can be implemented, or this drawback can be mentioned in the readme.

**Comment by AlenToma** [comment]
Oh, I really do not believe that. `DeepCloner` Uses `shadow Clone` and `reference Clone`. They do not use `IL Emit`.

I use both `IL Emit` and `reference clone` together, depending on different platform.

of course different platforms have different speed.

Could you please upload the test project you created so I could have a look?

**Comment by AlenToma** [comment]
Will be closing this since there is no supported argument that validate the claimes

**Comment by Sire** [comment]
It's legacy code so can't upload but it was hierarchical class structure 3 levels deep, around 14.000 parent objects, each with 1-3 child objects, and then around 1-6 child object to that class.
Classes also included 10-20 parameters each with normal datatypes (string, int, decimal, datetime) and some functions.

If you really don't believe me there might be a bug or a limitation somewhere? I might have some time next week to try to reproduce.
