### ISSUE TITLE
Cannot clone System.Uri

### ISSUE THREAD

**Issue by modenan** [AlenToma/FastDeepCloner#15]
Hi, your excellent utility cannot copy "System.Uri" objects.
I tried it in a .net 5 project. No error is reported during the cloning, but the cloned object doesn't contain the desired data.

**Comment by AlenToma** [comment]
Those that you are unable to clone, You could use this https://github.com/AlenToma/FastDeepCloner/blob/master/Documentations/NoneCloneableAttribute.md
