### ISSUE TITLE
Some things shouldn't be cloned

### ISSUE THREAD

**Issue by kcragin** [AlenToma/FastDeepCloner#18]
Some objects should not be cloned. I cloned a class that has a property of type `System.Type`. When the `DeepClone` method clones that property and you compare the original's property to the clone's property, they do not equal.

Something like this:

``` c#
public class MyClass
{
    Type MyType { get; set; }
}
```

Each `System.Type` representing a given loaded type should effectively be a singleton. For example, there is no such thing as two `typeof(System.Int32)` unless you are really loading two versions of the same assembly in a different load context, or two different assemblies with the same named type.

I like this library. It was hard to find one that worked well and didn't require default constructors.

Is there a work around for this issue? For now I am cloning and explicitly resetting the clone's property. I think in the case of certain types like `System.Type` you should just copy the reference allowing `ReferenceEquals` to be `true` for those cases.

**Comment by AlenToma** [comment]
You could use `NoneCloneableAttribute` as it copy those properties instead.
Read https://github.com/AlenToma/FastDeepCloner/blob/master/Documentations/NoneCloneableAttribute.md and see if it solve the problem.

**Comment by kcragin** [comment]
Thanks for the quick follow-up. That will do the trick!

On a separate note, if I have the time, would a PR to provide an API that causes certain types like `System.Type` to be copied by their reference instead of being cloned be of interest to you? If not, I understand.
