### ISSUE TITLE
Add credits ?

### ISSUE THREAD

**Issue by Skinz3** [AlenToma/FastDeepCloner#19]
https://grahammurray.wordpress.com/2010/04/13/dynamically-generating-types-to-implement-inotifypropertychanged/

**Comment by AlenToma** [comment]
What is it? This is something I made and did not copy from a their party

**Comment by Skinz3** [comment]
This is the exact same code. Why are you lying?

**Comment by Skinz3** [comment]
and it was released in 2010

**Comment by AlenToma** [comment]
I am really not lying. But I have no problem adding Credit. Could you till me where and what I should add it.
