### ISSUE TITLE
Incorrectly recognizes ReadOnlyCollection as List when call object.CloneTo()

### ISSUE THREAD

**Issue by GF-Huang** [AlenToma/FastDeepCloner#22]
![image](https://user-images.githubusercontent.com/4510984/154782069-5c36ce13-ef67-4149-bbc9-168fe040f781.png)

![image](https://user-images.githubusercontent.com/4510984/154782030-305493d7-0a3c-4c6e-b377-6c6bc801cf30.png)

**Comment by AlenToma** [comment]
Sadly it dose not support it yet. Use `List` instead.
