### ISSUE TITLE
StackOverflowException when deep cloning SwaggerDocsConfig

### ISSUE THREAD

**Issue by SmithPlatts** [AlenToma/FastDeepCloner#23]
Howdy!

Turns out I'm getting a genuine `System.StackOverflowException` when using FastDeepCloner and cloning a `Swashbuckle.Application.SwaggerDocsConfig` object.

Not sure what debugging info I can give, really.

OS: Windows 10 21H2
Visual Studio Version: 2019 Enterprise
Solution: .NET Framework 4.7.1
FastDeepCloner: 1.3.6

**Comment by SmithPlatts** [comment]
#### Addendum

Although our solution uses version 5.5.3 of the `Swashbuckle.Core` [NuGet package](https://www.nuget.org/packages/Swashbuckle.Core/5.5.3), I have confirmed that the same issue is encountered with the latest version: 5.6.0.

A simple repro can be achieved using either LINQPad or a console project:

``` csharp
FastDeepCloner.DeepCloner.Clone(new Swashbuckle.Application.SwaggerDocsConfig(), FastDeepCloner.FieldType.Both)
```

**Comment by AlenToma** [comment]
It is as it says `SwaggerDocsConfig` has some recursive issue that prevent the library from cloning.

This is related to `SwaggerDocsConfig` construction.

I think that you should use different approach to clone this. As creating a different class and try to manually copy the `SwaggerDocsConfig`.

**Comment by SmithPlatts** [comment]
The approach I went with in the end was to use [AnyClone](https://github.com/replaysMike/AnyClone), which is working without issue.

Thank you.
