### ISSUE TITLE
Managed Debugging Assistant 'FatalExecutionEngineError'  when attempting to clone TreeViewItem

### ISSUE THREAD

**Issue by sojatay** [AlenToma/FastDeepCloner#26]
Managed Debugging Assistant 'FatalExecutionEngineError' 
  Message=Managed Debugging Assistant 'FatalExecutionEngineError' : 'The runtime has encountered a fatal error. The address of the error was at 0x7419edb5, on thread 0x5644. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'

**Comment by AlenToma** [comment]
There seems to be some unsafe or something else in your class or object you are trying to clone.

The message you wrote do not tell me anything, Please try to include the class you are trying to clone.

It would be a great help if you could incl a running able example

**Comment by sojatay** [comment]
As described in the title, the object I am trying to clone is a TreeViewItem. It's actually a derived class inherited from TreeViewItem, but only has additional CLR Properties or DependencyProperties that are standard .NET classes/types. There is no unsafe or unmanaged code whatsoever (that I've written). It's not practical to include all the class here nor to include a running sample. It runs just fine, and the only reason I'm trying to use FastDeepCloner is because I have written my own cloner (which works ok on this class), but my cloner can't be described as "fast"; I wanted to compare the time my cloner takes, vs the time FastDeepCloner would take.

I've been writing .NET for about 18 years, and have to admit I've never previously seen a "Managed Debugging Assistant' error, so assumed that it was an error reported by your code! I have got no other information other than that which I gave you, which was a copy from the MessageBox reporting the error. There's no Stack Trace, so I've nowhere to start looking to see what might have caused the problem.

I guess I could load your code as another project in my solution and reference that instead of the Nuget Package, then try to trace the error using the debugger.

**Comment by AlenToma** [comment]
The problem, could be anything as fastdeepcloner uses reflection to clone and without looking at your code, it would be very difficult to find the issue. And yes it would be great if you could download the code and even fix it if it is possible and commit here. I would be glad to take a look and Inc it.

**Comment by sojatay** [comment]
I'll try that and let you know how I get on. My own cloner also uses Reflection, but doesn't currently have any problems with this class. That said - it did have all sorts of problems, but I've slowly whittled them away.

No other cloners I've tried have worked -the most common error being caused by StackOverflowException. That's why I decided to try to write my own.

 I'll get back to you if I can pinpoint where the problem is caused

**Comment by sojatay** [comment]
Looking quickly at your code, I see you have the following conditional compiler statement in your class INotifyPropertyChangedProxyTypeGenerator :

#if NETSTANDARD2_0 || NETCOREAPP2_0 || NET451

There are a number of other compiler conditionals referencing the OS elsewhere in your code, which all seem to be very OS-version specific.

I don't know how critical that is yet, because your commenting is a bit sparse (not a criticism; an observation), so it might take a while to work out how you're doing things

I'm actually using Net 4.7.2. Perhaps that conditional compiler directive might be better written as:

#if NETSTANDARD2_0 || NETCOREAPP2_0 || NET451_OR_GREATER

**Comment by sojatay** [comment]
The failure is occurring in FastDeepClonerProperty.cs at line 117:

     public void SetValue(object o, object value)
        {
            SetMethod(o, value);
        }

The value that's trying to be set is:  false

As far as I can tell,  object o is apparently of type System.RuntimeType.

 Debugger Locals says:

                     Name = Cannot evaluate expression because a native frame is on top of the call stack

Every one of o's properties says:

either:

                  " Cannot evaluate expression because a native frame is on top of the call stack"
 
or:

                   "Inspecting the state of an object in the debuggee of type System.Type is not supported in this context" (it actually says, debuggee instead of debugger

Changing the conditional compiler directive to 

#if NETSTANDARD2_0 || NETCOREAPP2_0 || NET451_OR_GREATER 

did not make any difference
