### ISSUE TITLE
CloneTo seems to behave differently than Clone regarding [FastDeepClonerPrimaryIdentifire] annotations

### ISSUE THREAD

**Issue by brecht-derooms** [AlenToma/FastDeepCloner#28]
Thanks for the library, it was the only lib that provided what I needed.
In the case that we have a structure (it might be that it only happens in more complex structures though).

object1.attr1 -> object2
object1.attr2 -> object2

Then it seems that object2 is not cloned with '**Clone**' which is perfect and what I would expect.
However, **CloneTo** seems to create duplicates of object2 in some cases although they have the same PrimariyIdentifire ID
A quick look at the code made me wonder whether there is a typo here: 

```
        internal object CloneTo(object itemToClone, object CloneToItem)
        {
            var identifier = CloneToItem.GetFastDeepClonerIdentifier();
            if (identifier != null && _alreadyCloned.ContainsKey(identifier))
                return _alreadyCloned[identifier];
```

in the Clone, the itemToClone is used for the identifier while here the 'to item' is used. I might be wrong, just took a quick look at the difference.

**Comment by AlenToma** [comment]
Yes it seems so, as the appending data will be added to `CloneToItem`, I have really not thought about this untill now.

but it should not be an issue for you just add the attribute to `CloneToItem` and I will have to fix this so that it could look at both. 

Thx for reporting the issue.

**Comment by AlenToma** [comment]
I was wrong,
If you look at the code below, so this is working as it should.

```
else if (prop.PropertyType == prop2.Value.PropertyType)
                        prop2.Value.SetValue(CloneToItem, value.Clone());
```
Do you have any issue?
