### ISSUE TITLE
Clone with values

### ISSUE THREAD

**Issue by rramirezg22** [AlenToma/FastDeepCloner#3]
Is there an option to clone an object including the current values of its properties?

I'm trying to clone an object of anonymous type and FastDeepCloner does the job but the values of the properties are the default and can´t be changed later.

thanks!

**Comment by AlenToma** [comment]
not understanding, could you provide an example code

**Comment by rramirezg22** [comment]
Yes!

using System;

namespace FastDeepClonerTest
{
	public class originalClass
	{
		public string prop1 { get; set; }
		public int prop2 { get; set; }
	}

	class Program
	{
		static void Main(string[] args)
		{
			originalClass originalObject = new originalClass();
			originalObject.prop1 = "p1";
			originalObject.prop2 = 10;
			var clonedObject = FastDeepCloner.DeepCloner.Clone(originalObject);

			// the structure of the clone object has been copied correctly
			// and the values too
			if (clonedObject.prop1 is null)
			{
				Console.WriteLine("prop1 of cloned object is null !!!");
			}
			else
			{
				// clonedObject.prop1 is "p1"
				Console.WriteLine("prop1 of cloned object is " + clonedObject.prop1);
			}

			dynamic originalAnonnymousObject = new
			{
				prop1 = "p1"
				, prop2 = 10
			};
			dynamic clonedAnonnymousObject = FastDeepCloner.DeepCloner.Clone(originalAnonnymousObject);
			// the structure of the clone object has been copied correctly
			// but the values are not
			if (clonedAnonnymousObject.prop1 is null)
			{
				// clonedAnonnymousObject.prop1 is null but should be "p1"
				Console.WriteLine("prop1 of cloned object is null !!!");
			}
			else
			{
				// clonedObject.prop1 is "p1"
				Console.WriteLine("prop1 of cloned object is " + clonedAnonnymousObject.prop1);
			}
		}
	}
}

**Comment by AlenToma** [comment]
Upgrade to FastDeepCloner 1.1.4 and use `CloneDynamic` to clone the AnonnymousType.
