### ISSUE TITLE
Unable to clone Xamarin.Forms.Button object

### ISSUE THREAD

**Issue by Lelelo1** [AlenToma/FastDeepCloner#4]
I am unable to clone a `Xamarin.Forms.Button` object.

I get a `System.NullReferenceException` trying to clone it with the default settings. Every other xamarin forms control is working so far. [Label](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Label.cs), [Slider](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Slider.cs) ,[Entry](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Entry.cs) etc works.

[Button](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Button.cs) doesn't work. Any idea why?

**Comment by AlenToma** [comment]
Those are UI object, why are you intressted in cloning them?

I cant gusse what the problem is and its really a waste of time getting into this. its better to handle this on your own by creating a new button and assign the text and click etc manually

**Comment by Lelelo1** [comment]
I am working on a custom ui list control. Where the developer can define what the rows look like by defining them in xaml. And then providing the reference of it to a build function.

I encountered [this](https://stackoverflow.com/questions/56405488/cant-create-content-with-datatemplate-in-code-behind-with-control-defined-in-xa) problem. (Basically that all controls are given an id - preventing them from being added more than once - from xaml into my custom list control)

By cloning them - a new id is given.

**Comment by AlenToma** [comment]
There is now a fix for this, have a look here https://github.com/AlenToma/FastDeepCloner/blob/master/Documentations/NoneCloneableAttribute.md
