### ISSUE TITLE
Please specify if xamarin.ios or corert or il2cpp supported (AOT)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [AlenToma/FastDeepCloner#5]
if you use il emit - will not work for sure

**Comment by AlenToma** [comment]
Its using `il emit` , `expression `and `GetUninitializedObject` Depending on platform. have you even tested it before applying this issue.  Have a look at [Creator Method](https://github.com/AlenToma/FastDeepCloner/blob/master/source/FastDeepCloner/FastDeepClonerCachedItems.cs) to understand how it work

**Comment by dzmitry-lahoda** [comment]
i have not tested, but this is the case for issue  - may be somebody done that work before.
